### ISSUE TITLE
SIGSEGV error in JRE when connecting to the database

### ISSUE THREAD

**Issue by Apoalex92** [koxudaxi/local-data-api#50]
Hello!
sometimes I run into the following error when runnning the _local-data-api_ container:

```
[2020-03-24 15:46:57 +0000] [7] [INFO] Waiting for application startup.
[2020-03-24 15:47:46 +0000] [7] [INFO] ('172.19.0.1', 43568) - "POST /BeginTransaction HTTP/1.1" 200
[2020-03-24 15:47:46 +0000] [7] [INFO] ('172.19.0.1', 43568) - "POST /RollbackTransaction HTTP/1.1" 500
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fef41ea0e69, pid=7, tid=0x00007fef49bc2b88
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.13.0
# Distribution: Custom build (Tue Oct  1 11:00:28 UTC 2019)
# Problematic frame:
# C  [_jpype.cpython-37m-x86_64-linux-gnu.so+0x28e69]  JPJavaEnv::NewLocalRef(_jobject*)+0x9
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /app/hs_err_pid7.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
[2020-03-24 15:47:46 +0000] [21] [INFO] Booting worker with pid: 21
[2020-03-24 15:47:46 +0000] [21] [INFO] Started server process [21]
[2020-03-24 15:47:46 +0000] [21] [INFO] Waiting for application startup.
```
The reported section is taken from `docker logs` of a container running the _local-data-api_ image.

It seems that the problem is related to the amount of memory space reserved to the JVM, as suggested into the stacktrace it could be useful to increase it.
I don't know how you could reproduce the problem, since it appears only sometime.

By the way, for further enhancement I suggest to remove the JDBC approach for connecting to database instances. Since the program is written in Python, it could be more efficient using **psycopg2** o **pymysql**.

**Comment by koxudaxi** [comment]
@Apoalex92 

Thank you for creating the issue.

> It seems that the problem is related to the amount of memory space reserved to the JVM, as suggested into the stacktrace it could be useful to increase it.

I will search for a method of how to increase reserved JVM memory size :+1: 

> By the way, for further enhancement I suggest to remove the JDBC approach for connecting to database instances. Since the program is written in Python, it could be more efficient using psycopg2 o pymysql.


I agree!! But, I choice JDBC driver for actual `ColumnMetadata`.

I made it with `pymysql` to access a DB.
However, I know we need to get `ColumnMetadata` with `includeResultMetadata`.
https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ColumnMetadata.html
I had found the metadata came from JDBC drivers. 
I had implemented it with the JDBC drivers. 
If we can create `ColumnMetadata` from  `pymysql`  or driver on python then I change JDBC  drivers to another driver on python.

Now, The code is broken to use `pymysql` in this app. I will fix it. Sorry.
However,  `ResultMetadata` is not correct. the quality is a mock level.

**Comment by agatim** [comment]
Hello!

If you want the column metadata you can query the table information_schema.columns (is available for Postgres and MySQL). Check the documentation:

PostgresSQL: https://www.postgresql.org/docs/9.1/infoschema-columns.html
MySQL: https://dev.mysql.com/doc/refman/8.0/en/columns-table.html

**Comment by koxudaxi** [comment]
@agatim 
I will check the documents!!
Thank you very much :smile:

**Comment by alexisespinosa** [comment]
Hi @koxudaxi 

I hit same error, is there a workaround? Saw your #69 pr but not sure if that fixes it

Thanks!

**Comment by koxudaxi** [comment]
Thank you for your reporting!!
It's awesome :rocket: 

I can't be waiting for the release of  `jpype` :laughing:

**Comment by koxudaxi** [comment]
I think this problem is resolved.
