### ISSUE TITLE
Support bigint

### ISSUE THREAD

**Issue by sdurban** [koxudaxi/local-data-api#53]
**Describe the bug**
When you try to get a table definition with a query like:

> SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'database' AND `TABLE_NAME` = 'user'

App will crash with the error:
> Exception: unsupported type <class 'jpype._jclass.java.math.BigInteger'>: 1

**To Reproduce**
In mysql/mariadb create a schema an try to get the table definition with a query like:

> POST https://localhost:8080/Execute
User-Agent: aws-sdk-nodejs/2.647.0 linux/v12.16.1 promise
Content-Type: application/json
{
  "secretArn": "arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy",
  "resourceArn": "arn:aws:rds:us-east-1:123456789012:cluster:dummy",
  "sql": "SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'database' AND `TABLE_NAME` = 'user'",
  "database": "database"
}

Docker will crash with this error:

![imagen](https://user-images.githubusercontent.com/4395258/78219787-8c067e00-74c0-11ea-941e-494b74ea9499.png)

**Expected behavior**
Like says in AWS Documentation (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html) it must return a LONG Data type.

![imagen](https://user-images.githubusercontent.com/4395258/78220091-25ce2b00-74c1-11ea-9dfe-9e6372258875.png)

**Comment by koxudaxi** [comment]
@sdurban 
Thank you for creating this issue and PR.

I didn't check the type. I'm happy :)

I have released a new version as `0.4.9`
you can pull it from DockerHub.

Thank you very much.

**Comment by sdurban** [comment]
@koxudaxi Thank you so much for the speedy merge ;)!
