### ISSUE TITLE
Refactor conversions-per-type

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/local-data-api#64]
We must refactor conversions-per-type.
This method is used for all DB resources.
It must be implemented per individual DB Resource.
https://github.com/koxudaxi/local-data-api/blob/5ef10d933af9fabdb671d80741ed6f5301707d15/local_data_api/models.py#L28-L53
## Motivation
This issue is forked from #62

> About PostgresSQL Engine (No JDBC)
> Making the query with python native connector returns a list:

> `unsupported type <class 'list'>: ['1', ' 2', ' 3', ' 4']`

> I think is kind of dangerous make a conversion from list to a schema like {1, 2, 3, 4}. Maybe it needs a refactor like conversions-per-type (JVM(PSQL/MYSQL) an non-JVM classes (PSQL and MYSQL separated)?
```

**Comment by sdurban** [comment]
Hello!

Since this issue is my fault, I will "try to make a PR" next week (if my fulltime job allows me).

**Comment by koxudaxi** [comment]
Thank you.
I may have too many active OSS projects :sweat_smile:
