### ISSUE TITLE
Support PGpoint

### ISSUE THREAD

**Issue by filipsuk** [koxudaxi/local-data-api#79]
**Is your feature request related to a problem? Please describe.**
All queries related to `point` postgres type fail.

**Describe the solution you'd like**
Add support for PGpoint. I think point should be handled as a string type similarly to pgarray https://github.com/koxudaxi/local-data-api/pull/63/files

**Additional context**
Using `ENGINE: PostgreSQLJDBC`

Exception:

```
Exception: unsupported type <java class 'org.postgresql.geometric.PGpoint'>: (50.074534,14.444137)
```

thanks this amazing library 👏

**Comment by koxudaxi** [comment]
@filipsuk 
Thank you for creating this issue.

OK, I will try it.

**Comment by koxudaxi** [comment]
@filipsuk 
I have pushed a new image as `0.5.2` 🚀 
This version parses all PostgreSQL geometric types as string

**Comment by filipsuk** [comment]
@koxudaxi amazing! thank you, works as expected 🎉
