### ISSUE TITLE
ExecuteSql is not implemented

### ISSUE THREAD

**Issue by rockstar** [koxudaxi/local-data-api#95]
Set up a local-data-api environment to test against, and once my application was able to execute sql against the application, I ran into a `NotImplementedError` in local-data-api. At first I thought I must be missing something in the config, but [looking at the source](https://github.com/koxudaxi/local-data-api/blob/master/local_data_api/main.py#L33) it appears that this really was never implemented. That seems to be a super basic usage of this tool, so it's kinda surprising to find that it's missing from a project that appears so mature and well-documented.

**To Reproduce**
Post anything to `/ExecuteSql`. A `NotImplementedError` will be raised.

**Expected behavior**
SQL is executed and results are returned.

**Comment by koxudaxi** [comment]
Thank you for creating this issue

> https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteSql.html

According to ExecuteSql is a deprecated API.
We should not use this feature.
I can implement it. But, who needs the feature? 🤔

**Comment by rockstar** [comment]
Ah, the tooling I was using had outdated docs and examples. I don't need this now, as I'm using `/ExecuteStatement`
